name: 'dip_rentenpolitik'
version: '1.0.0'
config-version: 2

profile: 'dip_rentenpolitik'

model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]

models:
  dip_rentenpolitik:
    staging:
      +materialized: view
    marts:
      +materialized: table